"""Integration checks against the real CSVs in `idx_picker/output/`.

These assert *internal consistency* of a completed run rather than any specific
number, because the files are regenerated by a full ~956-ticker refresh that may
be running while the suite executes. Every test therefore:

* skips cleanly when a file is missing or has fewer than 5 rows (a partial
  write), and
* never depends on a ticker count, a ticker list, or a particular company's
  figures.

What they are for: a metric can be individually correct and still be wired up
wrong. These tests catch the wiring -- a margin of safety that does not
reconcile to its own intrinsic value, a net-net flag that contradicts its own
threshold, an F-Score that does not equal the sum of its parts, a currency
conversion that never happened.
"""

from __future__ import annotations

import warnings

import pytest

from idx_picker.scraper import scoring as S

from .conftest import as_float

ALLOWED_VERDICTS = {S.VERDICT_BUY, S.VERDICT_WATCH, S.VERDICT_SKIP, S.VERDICT_DEEP_VALUE}

F_COMPONENT_COLUMNS = [
    "F: ROA Positive",
    "F: CFO Positive",
    "F: ROA Improving",
    "F: Accruals",
    "F: Leverage Falling",
    "F: Current Ratio Improving",
    "F: No Dilution",
    "F: Gross Margin Improving",
    "F: Asset Turnover Improving",
]


def _require_columns(rows, *columns):
    missing = [column for column in columns if column not in rows[0]]
    if missing:
        pytest.skip(f"columns absent from this run: {missing}")


# =================================================================== verdicts


def test_every_row_has_an_allowed_verdict(scores_rows):
    """Every scored row must carry one of the four defined verdicts.

    A blank or novel verdict string means a code path returned without deciding,
    and the workbook filters on this column -- an unrecognised value makes the
    row invisible rather than loudly wrong.
    """
    bad = [(row["Ticker"], row["Verdict"]) for row in scores_rows
           if row.get("Verdict") not in ALLOWED_VERDICTS]
    assert not bad, f"rows with an unrecognised verdict: {bad[:10]}"


def test_every_verdict_carries_a_reason(scores_rows):
    """A verdict without a reason cannot be audited.

    The reason string is the only record of *which* gate decided the outcome;
    without it a user cannot tell a SKIP for staleness from a SKIP for price.
    """
    bare = [row["Ticker"] for row in scores_rows if not (row.get("Reasons") or "").strip()]
    assert not bare, f"verdicts with no stated reason: {bare[:10]}"


# ================================================================ MOS coherence


def test_mos_blended_is_within_the_clamped_range(scores_rows):
    """`MOS Blended` is explicitly clamped to [-1, 1] and must respect it.

    Without the clamp an intrinsic value near zero produces four-digit negative
    percentages (-769,000% was observed for ADRO before the fix), which then
    dominate any sort on the column.
    """
    _require_columns(scores_rows, "MOS Blended")
    out_of_range = [
        (row["Ticker"], value)
        for row in scores_rows
        if (value := as_float(row.get("MOS Blended"))) is not None
        and not (-1.0 <= value <= 1.0)
    ]
    assert not out_of_range, f"MOS Blended outside [-1, 1]: {out_of_range[:10]}"


def test_mos_blended_reconciles_to_intrinsic_value_and_price(scores_rows):
    """MOS must equal (IV - Price)/IV wherever both legs are present and IV > 0.

    This is the one arithmetic identity a user will check by hand. A mismatch
    means the MOS was computed against a different intrinsic value than the one
    reported -- e.g. a scenario IV rather than the blended one -- which makes
    the whole row internally inconsistent.

    Rows at the clamp boundary are exempt, since the clamp is deliberately not
    an identity.
    """
    _require_columns(scores_rows, "MOS Blended", "Blended IV", "Price")
    mismatches = []
    checked = 0
    for row in scores_rows:
        iv = as_float(row.get("Blended IV"))
        price = as_float(row.get("Price"))
        mos = as_float(row.get("MOS Blended"))
        if iv is None or price is None or mos is None or iv <= 0:
            continue
        expected = (iv - price) / iv
        if expected <= -1.0 or expected >= 1.0:
            continue  # clamped on purpose
        checked += 1
        if abs(expected - mos) > 1e-6:
            mismatches.append((row["Ticker"], mos, expected))
    if not checked:
        pytest.skip("no rows with both a positive blended IV and a price")
    assert not mismatches, f"MOS does not reconcile to (IV - Price)/IV: {mismatches[:10]}"


def test_upside_and_mos_are_consistent_with_each_other(scores_rows):
    """Upside = IV/Price - 1 and MOS = 1 - Price/IV are the same fact, two ways.

    They must satisfy `upside = mos / (1 - mos)`. Reporting one where the other
    belongs is the most common way a screener overstates an opportunity.
    """
    _require_columns(scores_rows, "MOS Blended", "Upside Blended", "Blended IV", "Price")
    bad = []
    for row in scores_rows:
        iv, price = as_float(row.get("Blended IV")), as_float(row.get("Price"))
        mos, upside = as_float(row.get("MOS Blended")), as_float(row.get("Upside Blended"))
        if None in (iv, price, mos, upside) or iv <= 0 or price <= 0:
            continue
        if abs(mos - 1.0) < 1e-9 or not (-1.0 < mos < 1.0):
            continue  # clamped
        if abs(upside - mos / (1 - mos)) > 1e-4:
            bad.append((row["Ticker"], mos, upside))
    assert not bad, f"MOS and upside disagree: {bad[:10]}"


def test_scenario_intrinsic_values_are_ordered_bear_base_bull(scores_rows):
    """Wherever all three scenario IVs are present they must be strictly ordered.

    The bear/base/bull columns are read as a range; an inverted range is worse
    than no range, because it looks authoritative.
    """
    _require_columns(scores_rows, "IV Bear", "IV Base", "IV Bull")
    inverted = []
    for row in scores_rows:
        bear, base, bull = (as_float(row.get(column))
                            for column in ("IV Bear", "IV Base", "IV Bull"))
        if None in (bear, base, bull):
            continue
        if not (bear <= base <= bull):
            inverted.append((row["Ticker"], bear, base, bull))
    assert not inverted, f"scenario IVs out of order (bear/base/bull): {inverted[:10]}"


# ================================================================== net-net flag


def test_net_net_pass_actually_satisfies_the_two_thirds_rule(scores_rows):
    """`Net-Net Pass` = TRUE must mean Price < (2/3) x NCAV per share.

    The flag drives a distinct DEEP VALUE verdict, so a false positive puts a
    company with no asset protection into the highest-conviction Graham bucket.
    """
    _require_columns(scores_rows, "Net-Net Pass", "NCAV per Share", "Price")
    violations = []
    passes = 0
    for row in scores_rows:
        if (row.get("Net-Net Pass") or "").strip().upper() not in {"TRUE", "1", "YES"}:
            continue
        passes += 1
        ncav, price = as_float(row.get("NCAV per Share")), as_float(row.get("Price"))
        if ncav is None or price is None:
            violations.append((row["Ticker"], "missing NCAV or price"))
        elif not price < (2.0 / 3.0) * ncav:
            violations.append((row["Ticker"], price, ncav, (2.0 / 3.0) * ncav))
    assert not violations, f"Net-Net Pass rows failing the 2/3 rule: {violations[:10]}"
    if passes == 0:
        warnings.warn(
            "no Net-Net Pass rows in this sample - the 2/3 rule check was vacuous",
            UserWarning,
        )


def test_deep_value_verdicts_are_backed_by_the_net_net_flag(scores_rows):
    """DEEP VALUE is reachable only through the net-net branch of `classify`.

    If a DEEP VALUE verdict ever appears without the flag, the verdict logic has
    grown a second, untested path into the highest-conviction bucket.
    """
    _require_columns(scores_rows, "Net-Net Pass", "Verdict")
    stray = [row["Ticker"] for row in scores_rows
             if row.get("Verdict") == S.VERDICT_DEEP_VALUE
             and (row.get("Net-Net Pass") or "").strip().upper() not in {"TRUE", "1", "YES"}]
    assert not stray, f"DEEP VALUE without a net-net flag: {stray[:10]}"


# ==================================================================== F-Score


def test_f_score_is_an_integer_in_range_or_blank(key_stats_rows):
    """The Piotroski total must be a whole number 0-9, or absent.

    A fractional or out-of-range value means signals are being summed with
    something other than 0/1, and the value gates a WATCH at <= 3.
    """
    _require_columns(key_stats_rows, "Piotroski F-Score")
    bad = []
    for row in key_stats_rows:
        raw = (row.get("Piotroski F-Score") or "").strip()
        if not raw:
            continue
        value = as_float(raw)
        if value is None or value != int(value) or not (0 <= value <= 9):
            bad.append((row["Ticker"], raw))
    assert not bad, f"F-Score values that are not integers 0-9: {bad[:10]}"


def test_f_score_components_sum_to_the_reported_total(key_stats_rows):
    """The nine `F:` columns must sum to the total whenever the total is present.

    The breakdown is what makes the score auditable. If it does not add up, one
    of the two is stale or the blank-handling differs between them -- and the
    breakdown is the only way a user can tell a genuine 2/9 from a 2/9 built out
    of seven blanks.
    """
    _require_columns(key_stats_rows, "Piotroski F-Score", *F_COMPONENT_COLUMNS)
    mismatches = []
    for row in key_stats_rows:
        total = as_float(row.get("Piotroski F-Score"))
        if total is None:
            continue
        parts = sum(as_float(row.get(column)) or 0.0 for column in F_COMPONENT_COLUMNS)
        if abs(parts - total) > 1e-9:
            mismatches.append((row["Ticker"], total, parts))
    assert not mismatches, f"F-Score does not equal the sum of its components: {mismatches[:10]}"


def test_f_score_components_are_zero_one_or_blank(key_stats_rows):
    """Each signal is a binary vote; anything else is not a Piotroski signal."""
    _require_columns(key_stats_rows, *F_COMPONENT_COLUMNS)
    bad = []
    for row in key_stats_rows:
        for column in F_COMPONENT_COLUMNS:
            raw = (row.get(column) or "").strip()
            if raw and raw not in {"0", "1"}:
                bad.append((row["Ticker"], column, raw))
    assert not bad, f"non-binary F-Score components: {bad[:10]}"


def test_f_score_agrees_between_the_scores_and_key_statistics_files(scores_rows, key_stats_rows):
    """The same score must not differ between the two files a user reads.

    Both sheets are consumed by the workbook; a divergence means one of them is
    written from a stale assessment object.
    """
    _require_columns(scores_rows, "F-Score")
    _require_columns(key_stats_rows, "Piotroski F-Score")
    by_ticker = {row["Ticker"]: as_float(row.get("Piotroski F-Score")) for row in key_stats_rows}
    mismatches = [
        (row["Ticker"], as_float(row.get("F-Score")), by_ticker[row["Ticker"]])
        for row in scores_rows
        if row["Ticker"] in by_ticker
        and as_float(row.get("F-Score")) != by_ticker[row["Ticker"]]
    ]
    assert not mismatches, f"F-Score differs between the two files: {mismatches[:10]}"


def test_f_score_signal_coverage_is_reported(key_stats_rows):
    """Surface how often each Piotroski signal is unevaluable across the universe.

    Not a pass/fail assertion: a signal that is blank for *every* ticker is a
    data-plumbing failure rather than a company-level fact, and it silently
    consumes the three-blank budget that `metrics._total` allows before it gives
    up and returns None.
    """
    _require_columns(key_stats_rows, *F_COMPONENT_COLUMNS)
    total = len(key_stats_rows)
    blanks = {
        column: sum(1 for row in key_stats_rows if not (row.get(column) or "").strip())
        for column in F_COMPONENT_COLUMNS
    }
    always_blank = [column for column, count in blanks.items() if count == total]
    warnings.warn(
        f"F-Score signal blanks over {total} rows: "
        + ", ".join(f"{c.replace('F: ', '')}={n}" for c, n in blanks.items()),
        UserWarning,
    )
    if always_blank:
        warnings.warn(
            "DATA DEFECT: these Piotroski signals are unevaluable for EVERY ticker, "
            f"capping the achievable F-Score: {always_blank}",
            UserWarning,
        )


# ================================================================ ticker joins


def test_every_key_statistics_ticker_appears_in_scores_and_listings(
    key_stats_rows, scores_rows, idx_stock_rows
):
    """The three output files must describe the same universe.

    The workbook joins them on ticker. A name present in one and missing from
    another produces half-populated rows -- statistics with no verdict, or a
    verdict with no price -- which is the failure mode most likely to be read as
    a real signal.
    """
    stats = {row["Ticker"] for row in key_stats_rows}
    scored = {row["Ticker"] for row in scores_rows}
    listed = {row["Ticker"] for row in idx_stock_rows}
    assert not (stats - scored), f"in key statistics but not scored: {sorted(stats - scored)[:10]}"
    assert not (stats - listed), f"in key statistics but not listed: {sorted(stats - listed)[:10]}"


def test_tickers_are_unique_within_each_file(scores_rows, key_stats_rows, idx_stock_rows):
    """A duplicated ticker double-counts the name in any ranking built on the file."""
    for name, rows in (("scores", scores_rows), ("key statistics", key_stats_rows),
                       ("listings", idx_stock_rows)):
        tickers = [row["Ticker"] for row in rows]
        duplicates = {ticker for ticker in tickers if tickers.count(ticker) > 1}
        assert not duplicates, f"duplicate tickers in {name}: {sorted(duplicates)[:10]}"


# ============================================================ currency guard


def test_non_idr_filers_have_a_real_fx_rate(key_stats_rows):
    """A USD-reporting filer must not be converted at 1.0.

    Several IDX issuers -- the coal and energy names especially (ITMG, ADRO,
    INDY) -- report in USD while their shares trade in IDR. An FX rate of 1.0
    against a USD statement understates every per-share figure by ~16,000x,
    which turns a fairly valued company into an apparent 99.99% discount. This
    is the single highest-impact silent error available in the pipeline.
    """
    _require_columns(key_stats_rows, "Statement Currency", "FX Rate Applied")
    offenders = []
    non_idr = 0
    for row in key_stats_rows:
        currency = (row.get("Statement Currency") or "").strip().upper()
        if not currency or currency == "IDR":
            continue
        non_idr += 1
        rate = as_float(row.get("FX Rate Applied"))
        if rate is None or rate == pytest.approx(1.0):
            offenders.append((row["Ticker"], currency, row.get("FX Rate Applied")))
    assert not offenders, f"non-IDR filers with an FX rate of 1.0: {offenders[:10]}"
    if non_idr == 0:
        warnings.warn("no non-IDR filers in this sample - the FX guard was vacuous",
                      UserWarning)


def test_idr_filers_are_not_double_converted(key_stats_rows):
    """An IDR-reporting filer must be converted at exactly 1.0.

    The inverse error: applying a rate to statements already denominated in IDR
    inflates every figure by the same ~16,000x.
    """
    _require_columns(key_stats_rows, "Statement Currency", "FX Rate Applied")
    offenders = [
        (row["Ticker"], row.get("FX Rate Applied"))
        for row in key_stats_rows
        if (row.get("Statement Currency") or "").strip().upper() == "IDR"
        and as_float(row.get("FX Rate Applied")) != pytest.approx(1.0)
    ]
    assert not offenders, f"IDR filers with an FX rate other than 1.0: {offenders[:10]}"


# ========================================================== staleness coherence


def test_stale_rows_are_skipped(scores_rows):
    """The staleness rule in `classify` must be visible in the output.

    Anything more than three quarters stale has to be SKIP; if a stale row
    carries a BUY the gate is not wired into the run that produced the file.
    """
    _require_columns(scores_rows, "Quarters Stale", "Verdict")
    leaks = [
        (row["Ticker"], row["Quarters Stale"], row["Verdict"])
        for row in scores_rows
        if (stale := as_float(row.get("Quarters Stale"))) is not None
        and stale > 3.0 and row.get("Verdict") != S.VERDICT_SKIP
    ]
    assert not leaks, f"stale rows that were not skipped: {leaks[:10]}"


# ========================================================= data-quality report


def test_report_out_of_band_ratios(key_stats_rows):
    """Report -- not fail on -- ratios outside plausible bands.

    PE outside [-1000, 1000], PB outside [0, 100] and ROE outside [-10, 10] are
    almost always upstream data problems (a near-zero denominator, a share count
    off by an order of magnitude, an unconverted currency) rather than real
    companies. They are surfaced as warnings because the correct response is to
    investigate the source row, not to fail a build: the universe legitimately
    contains a few distressed names with extreme ratios.
    """
    bands = {
        "Current PE Ratio (TTM)": (-1000.0, 1000.0),
        "Current Price to Book Value": (0.0, 100.0),
        "Return on Equity (TTM)": (-10.0, 10.0),
    }
    _require_columns(key_stats_rows, *bands)
    report: list[str] = []
    for column, (low, high) in bands.items():
        offenders = [
            (row["Ticker"], value)
            for row in key_stats_rows
            if (value := as_float(row.get(column))) is not None and not (low <= value <= high)
        ]
        report.append(f"{column} outside [{low}, {high}]: {len(offenders)}"
                      + (f" e.g. {offenders[:5]}" if offenders else ""))
    warnings.warn("DATA QUALITY over %d rows -- " % len(key_stats_rows) + " | ".join(report),
                  UserWarning)
    # Only a wholesale corruption should fail: more than half the universe out of band.
    for column, (low, high) in bands.items():
        values = [value for row in key_stats_rows
                  if (value := as_float(row.get(column))) is not None]
        if not values:
            continue
        out = sum(1 for value in values if not (low <= value <= high))
        assert out <= len(values) / 2, (
            f"{column}: {out}/{len(values)} rows out of band - systematic corruption"
        )


def test_report_verdict_distribution(scores_rows):
    """Report the verdict mix so a run that classifies everything alike is visible.

    A screener returning BUY for 90% of the universe, or SKIP for 100%, is
    broken in a way no individual row assertion catches.
    """
    counts: dict[str, int] = {}
    for row in scores_rows:
        counts[row.get("Verdict", "")] = counts.get(row.get("Verdict", ""), 0) + 1
    warnings.warn(f"verdict distribution over {len(scores_rows)} rows: {counts}", UserWarning)
    assert max(counts.values()) < len(scores_rows) or len(counts) == 1, "unreachable"
    if len(counts) == 1:
        warnings.warn(f"every row received the same verdict: {counts}", UserWarning)


def test_report_blended_iv_coverage(scores_rows):
    """Report how many rows got no intrinsic value at all.

    A row with no blended IV cannot be ranked on value, so coverage is the
    practical ceiling on what the screen can say about the universe.
    """
    _require_columns(scores_rows, "Blended IV")
    missing = [row["Ticker"] for row in scores_rows if as_float(row.get("Blended IV")) is None]
    warnings.warn(
        f"blended IV missing for {len(missing)}/{len(scores_rows)} rows: {missing[:15]}",
        UserWarning,
    )
